site_name: Jeff's Blog
site_author: Jeff Liu
site_url: https://jeffliulab.github.io/blog/

theme:
  name: material
  features:
    - navigation.sections
    # - navigation.expand

plugins:
  - search
  - i18n: # https://ultrabug.github.io/mkdocs-static-i18n/fr/getting-started/quick-start/
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 中文
          build: true

nav:
  - Home: index.md
  - Algorithms Diaries: notes_algorithms/diary_algorithms_2025.md

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - stylesheets/extra.css