site_name: Jeff's Algorithm and Leetcode Notes
site_author: Jeff Liu
site_url: https://jeffliulab.github.io/algorithm-notes/

theme:
  name: material
  features:
    - navigation.sections
    # - navigation.expand

plugins:
  - search
  - i18n: # https://ultrabug.github.io/mkdocs-static-i18n/fr/getting-started/quick-start/
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 中文
          build: true

nav:
  - INTRO: index.md
  - Common:
    - 算法宝典: 算法宝典.md
    - Data Structures: data_structures.md
    - Leetcode Temporary: Leetcode/leetcode.md
  - Machine Learning:
    - 常见面试问题: ML/index.md
  - Hard Questions:
    - Hard_Questions: Hard/hard_01.md

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - stylesheets/extra.css